-- Seed data is managed by scripts/seed-demo.ts
-- Run: pnpm seed:demo
--
-- This file is kept for Supabase CLI compatibility (supabase db reset).
-- It intentionally does nothing — the TypeScript seed handles everything.
